eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: quant-gather-store-service
  zipkin:
    base-url: http://localhost:9411
feign:
  hystrix:
    enabled: false
  compression:
    request:
      enabled: true #开启请求压缩
    response:
      enabled: true #开启请求压缩
#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 9000
#ribbon的超时时间
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#      cors:
#        allowed-origins: "*"
#        allowed-methods: "*"
ok:
  http:
    connect-timeout: 30
    read-timeout: 30
    write-timeout: 30
    max-idle-connections: 200
    keep-alive-duration: 300
